/**
 * Blueprint Node - Generates project blueprint using PlanningService
 * Uses autonomous multi-phase planning for dynamic feature ideation
 */

import { WebsiteState, ProjectBlueprint } from '../graph-state';
import { storeBlueprintMemory, clearProjectMemory, generateProjectId } from '../memory-utils';
import { fetchProjectImages, storeImagesInMemory, UnsplashImage } from '../services/image.service';
import { PlanningService } from '../../../services/planning-fixed.service';
import { Planning3DService } from '../../../services/planning-3d.service';
import { generateDynamicTheme } from '../../../services/dynamic-trends.service';
import { initProjectMemory } from '../project-memory';

// Complete list of dependencies
const STANDARD_DEPENDENCIES: Record<string, string> = {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^7.1.1",
    "framer-motion": "^11.14.4",
    "lucide-react": "^0.460.0",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.5",
    "react-hook-form": "^7.54.0",
    "@hookform/resolvers": "^3.9.1",
    "zod": "^3.24.1",
    "zustand": "^5.0.2",
    "@tanstack/react-query": "^5.62.2",
    "axios": "^1.7.9",
    "sonner": "^1.7.3",
    "date-fns": "^4.1.0",
    "gsap": "^3.12.5"
};

const THREE_JS_DEPENDENCIES: Record<string, string> = {
    "three": "^0.170.0",
    "@react-three/fiber": "^8.17.10",
    "@react-three/drei": "^9.117.3",
    "@react-three/postprocessing": "^2.16.3",
    "leva": "^0.9.35",
    "@types/three": "^0.170.0"
};

const DEV_DEPENDENCIES: Record<string, string> = {
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@types/node": "^22.10.2",
    "@vitejs/plugin-react": "^4.3.4",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.49",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.7.2",
    "vite": "^6.0.5",
    "eslint": "^9.16.0"
};

export async function blueprintNode(state: WebsiteState): Promise<Partial<WebsiteState>> {
    console.log('\n ═══════════════════════════════════════════');
    console.log(' NODE: BLUEPRINT (DYNAMIC PLANNING)');
    console.log(' ═══════════════════════════════════════════\n');

    try {
        console.log(' Starting autonomous planning...');
        console.log(`   User Request: "${state.userPrompt.slice(0, 100)}..."`);
        console.log(`   Project Type: ${state.projectType || 'frontend'}`);

        // Step 1: Absolute early-exit guard for 3D Mode
        const is3D = state.enable3D === true || (state as any).is3DMode === true || state.userPrompt.toLowerCase().includes('3d') || (state.projectType as string) === '3d';

        // Extract business name early for both
        const lockedBusinessName = extractBusinessName(state.userPrompt);

        // ── FAST-PATH: blueprint was already generated by /planning endpoint ──
        // Trust skipBlueprintGeneration flag unconditionally — no length gate needed
        if (state.skipBlueprintGeneration) {
            console.log(`   [Blueprint] SKIP MODE: Using pre-generated context (${state.userPrompt.length} chars)`);
            console.log(`   [Blueprint] Skipping planning service call entirely.`);

            const detailedCtx = state.userPrompt;

            // Extract project name from JSON in the detailedContext (planning service embeds it)
            const nameInJson = detailedCtx.match(/"projectName"\s*:\s*"([^"]+)"/);
            const resolvedName = nameInJson ? nameInJson[1] : lockedBusinessName;

            // Generate theme without calling any planning service
            const sharedTheme = generateDynamicTheme(detailedCtx.slice(0, 800));

            // Extract pages with LLM from the existing context
            const dynamicPages = await extractPagesWithLLM(detailedCtx, detailedCtx, []);

            const blueprint: ProjectBlueprint = {
                projectName: resolvedName,
                description: '',
                features: [],
                pages: dynamicPages.map((p: any) => ({ ...p, name: p.name.replace(/\s+/g, '') })),
                components: is3D ? [] : extractComponentsFromContext(detailedCtx),
                designSystem: extractDesignSystem(detailedCtx),
                dependencies: is3D
                    ? {
                        "react": "^18.3.1",
                        "react-dom": "^18.3.1",
                        "react-router-dom": "^7.1.1",
                        "framer-motion": "^11.14.4",
                        "clsx": "^2.1.1",
                        "tailwind-merge": "^2.5.5",
                        "gsap": "^3.12.5",
                        "three": "^0.170.0",
                        "@react-three/fiber": "^8.17.10",
                        "@react-three/drei": "^9.117.3",
                        "@react-three/postprocessing": "^2.16.3",
                        "leva": "^0.9.35",
                    }
                    : { ...STANDARD_DEPENDENCIES }
            };

            // Apply 3D package filtering and injection
            if (state.enable3D) {
                const BLOCKED_2D_PACKAGES = new Set([
                    'stripe', '@stripe/stripe-js', '@stripe/react-stripe-js',
                    'swiper', 'react-hot-toast', 'sonner',
                    'recharts', '@radix-ui/react-icons', 'lucide-react',
                    'react-icons', '@heroicons/react',
                    'embla-carousel-react', 'react-slick', 'slick-carousel',
                ]);
                const filteredExt: Record<string, string> = {};
                for (const [pkg, ver] of Object.entries(sharedTheme.extendedPackages)) {
                    if (!BLOCKED_2D_PACKAGES.has(pkg)) filteredExt[pkg] = ver as string;
                }
                sharedTheme.extendedPackages = filteredExt;

                blueprint.dependencies = {
                    ...blueprint.dependencies,
                    ...THREE_JS_DEPENDENCIES,
                    '@react-three/postprocessing': '^2.16.0',
                    'postprocessing': '^6.35.0',
                };
            }

            blueprint.dependencies = { ...blueprint.dependencies, ...sharedTheme.extendedPackages };

            const projectId = generateProjectId(blueprint.projectName);
            await clearProjectMemory(projectId);
            await storeBlueprintMemory(projectId, blueprint);

            let availableImages: any[] = [];
            try {
                availableImages = await fetchProjectImages(detailedCtx.slice(0, 500));
                if (availableImages.length > 0) await storeImagesInMemory(projectId, availableImages);
            } catch { /* non-fatal */ }

            const stateWithBlueprint = { ...state, blueprint, dynamicTheme: sharedTheme } as WebsiteState;
            const projectMemory = initProjectMemory(stateWithBlueprint);
            if (state.enable3D) {
                projectMemory.threeDDependencies = { ...THREE_JS_DEPENDENCIES };
                projectMemory.narrativeStyle = `CINEMATIC 3D EXPERIENCE: Create an Awwwards-level immersive 3D website for: ${detailedCtx.slice(0, 300)}.
QUALITY: Every scene must be a MURAL (200+ lines, custom shaders, particle systems, scroll narratives) not a thumbnail.
SCROLL NARRATIVE: Map useScroll().offset to 3-act arc (Establish->Reveal->Resolve).
CAMERA: Use CatmullRomCurve3 for cinematic camera fly-throughs on hero scenes.
SHADERS: Include custom ShaderMaterial with vertexShader + fragmentShader + uTime for atmospheric backgrounds.
PARTICLES: Use BufferGeometry particle morphing systems that transition between shapes on scroll.
POSTPROCESSING: Bloom, Vignette, ChromaticAberration animated with scroll via refs.
Canvas: gl={{ antialias: true, alpha: false, powerPreference: "high-performance" }} dpr={[1,2]} shadows camera={{ fov: 60, near: 0.1, far: 1000 }}
ScrollControls: pages={8} damping={0.03}
Performance: <AdaptiveDpr pixelated /> <AdaptiveEvents />`;
            }

            console.log(`\n [Blueprint] Skip-mode complete: "${blueprint.projectName}"`);
            console.log(`    Pages: ${blueprint.pages.length}`);

            return {
                blueprint,
                projectId,
                availableImages,
                dynamicTheme: sharedTheme,
                projectMemory,
                detailedContext: detailedCtx,
                workflowNodes: [],
                workflowEdges: [],
                currentPhase: 'blueprint',
                messages: [
                    ` Pre-Generated Blueprint Reused: ${blueprint.projectName}`,
                    ` Theme: ${sharedTheme.palette.name} + ${sharedTheme.layout.name}`,
                    ` ${blueprint.pages.length} pages determined`,
                    state.enable3D ? ` 3D dependencies injected` : ''
                ].filter(Boolean)
            };
        }
        // ── END FAST-PATH ──

        // Hard stop: if skipBlueprintGeneration is set, planning service must NOT run again.
        // This should have already returned above via the fast-path. If we somehow reach
        // here with skipBlueprintGeneration=true it means the prompt was too short to
        // carry a full detailedContext — throw a clear error rather than double-calling.
        if (state.skipBlueprintGeneration) {
            throw new Error(
                '[Blueprint] skipBlueprintGeneration=true but fast-path did not activate. ' +
                'detailedContext from /planning may have been empty — check Planning3DService response.'
            );
        }

        let planningResponse;
        let sharedTheme;

        if (is3D) {
            console.log(`   [Blueprint] 3D MODE DETECTED EARLY -- locked business name: "${lockedBusinessName}"`);
            console.log(`   [Blueprint] Bypassing all 2D planning services.`);

            // Generate the shared theme ONCE, so Planning3DService and the rest of the pipeline use the EXACT SAME theme
            sharedTheme = generateDynamicTheme(state.userPrompt);

            // For 3D mode, rely on Planning3DService
            planningResponse = await Planning3DService.generateBlueprint(
                state.userPrompt,
                0,
                state.projectType || 'frontend',
                sharedTheme
            );
        } else {
            console.log(`   [Blueprint] 2D MODE DETECTED -- locked business name: "${lockedBusinessName}"`);
            // Call DynamicTrends exactly once for 2D
            sharedTheme = generateDynamicTheme(state.userPrompt);

            planningResponse = await PlanningService.generateBlueprint(
                state.userPrompt,
                0,
                state.projectType || 'frontend',
                false,
                sharedTheme
            );
        }

        if (!planningResponse?.success || !planningResponse?.data) {
            throw new Error(planningResponse?.error || 'Planning failed');
        }

        const planBlueprint = planningResponse.data.blueprint;

        // Step 4: Override project name
        if (is3D && lockedBusinessName && planBlueprint.projectName !== lockedBusinessName) {
            planBlueprint.projectName = lockedBusinessName;
            console.log(`   [Blueprint] Overrode project name -> "${lockedBusinessName}"`);
        }

        // Use LLM to dynamically generate project-specific pages
        console.log('    Generating unique pages with LLM...');
        const dynamicPages = await extractPagesWithLLM(
            state.userPrompt,
            planBlueprint.detailedContext,
            planBlueprint.features
        );

        // Convert PlanningService blueprint to LangGraph ProjectBlueprint format
        const blueprint: ProjectBlueprint = {
            projectName: planBlueprint.projectName,
            description: planBlueprint.description,
            features: planBlueprint.features.map(f => ({
                name: typeof f === 'string' ? f : f,
                description: typeof f === 'string' ? f : f,
                priority: 'high' as const
            })),
            pages: dynamicPages,
            components: extractComponentsFromContext(planBlueprint.detailedContext),
            designSystem: extractDesignSystem(planBlueprint.detailedContext),
            dependencies: is3D
                ? {
                    "react": "^18.3.1",
                    "react-dom": "^18.3.1",
                    "react-router-dom": "^7.1.1",
                    "framer-motion": "^11.14.4",
                    "clsx": "^2.1.1",
                    "tailwind-merge": "^2.5.5",
                    "gsap": "^3.12.5",
                    "three": "^0.170.0",
                    "@react-three/fiber": "^8.17.10",
                    "@react-three/drei": "^9.117.3",
                    "@react-three/postprocessing": "^2.16.3",
                    "leva": "^0.9.35",
                }
                : { ...STANDARD_DEPENDENCIES }
        };

        // Ensure page names are valid
        blueprint.pages = blueprint.pages.map(page => ({
            ...page,
            name: page.name.replace(/\s+/g, '')
        }));

        console.log(`\n Dynamic Blueprint Created: ${blueprint.projectName}`);
        console.log(`    Pages: ${blueprint.pages.length} (dynamically determined)`);
        console.log(`    Components: ${blueprint.components.length}`);
        console.log(`    Features: ${blueprint.features.length}`);
        console.log(`    Workflow Nodes: ${planBlueprint.workflow?.nodes?.length || 0}`);

        // Log the pages for visibility
        blueprint.pages.forEach(p => console.log(`      → ${p.name} (${p.route})`));

        // Generate project ID for Mem0 tracking
        const projectId = generateProjectId(blueprint.projectName);
        console.log(`    Project ID: ${projectId}`);

        // Clear any previous memory for this project and store new blueprint
        await clearProjectMemory(projectId);
        await storeBlueprintMemory(projectId, blueprint);

        // Fetch images from the image microservice
        console.log('\n  Fetching project images...');
        let availableImages: UnsplashImage[] = [];
        try {
            availableImages = await fetchProjectImages(state.userPrompt);
            if (availableImages.length > 0) {
                await storeImagesInMemory(projectId, availableImages);
                console.log(` ${availableImages.length} images fetched and stored`);
            } else {
                console.log(' No images fetched - will use gradient placeholders');
            }
        } catch (imgError: any) {
            console.error(` Image fetching failed: ${imgError.message} - will use gradients`);
        }

        // Use the shared theme generated earlier
        const dynamicTheme = sharedTheme;
        console.log(`\n Shared Dynamic Theme: ${dynamicTheme.palette.name}`);
        console.log(`    Layout: ${dynamicTheme.layout.name}`);
        console.log(`    Animation: ${dynamicTheme.animation.name}`);
        console.log(`    Extended Packages: ${Object.keys(dynamicTheme.extendedPackages).join(', ')}`);

        if (state.enable3D) {
            const BLOCKED_2D_PACKAGES = new Set([
                'stripe', '@stripe/stripe-js', '@stripe/react-stripe-js',
                'swiper', 'react-hot-toast', 'sonner',
                'recharts', '@radix-ui/react-icons', 'lucide-react',
                'react-icons', '@heroicons/react',
                'embla-carousel-react', 'react-slick', 'slick-carousel',
            ]);
            const filtered: Record<string, string> = {};
            for (const [pkg, ver] of Object.entries(dynamicTheme.extendedPackages)) {
                if (!BLOCKED_2D_PACKAGES.has(pkg)) {
                    filtered[pkg] = ver as string;
                } else {
                    console.log(`    [blueprint] Filtered 2D package: ${pkg}`);
                }
            }
            dynamicTheme.extendedPackages = filtered;
        }

        blueprint.dependencies = {
            ...blueprint.dependencies,
            ...dynamicTheme.extendedPackages
        };

        if (state.enable3D) {
            blueprint.dependencies = {
                ...blueprint.dependencies,
                ...THREE_JS_DEPENDENCIES,
                '@react-three/postprocessing': '^2.16.0',
                'postprocessing': '^6.35.0',
            };

            blueprint.components = [];
            blueprint.features = blueprint.features || [];

            console.log(`[blueprint] Pure 3D architecture: cleared 2D components, injected 3D + postprocessing deps`);
            console.log(`[blueprint] 3D dependencies: ${Object.keys(THREE_JS_DEPENDENCIES).join(', ')}, @react-three/postprocessing`);
        }

        const stateWithBlueprint = { ...state, blueprint, dynamicTheme } as WebsiteState;
        const projectMemory = initProjectMemory(stateWithBlueprint);
        if (state.enable3D) {
            projectMemory.threeDDependencies = { ...THREE_JS_DEPENDENCIES };
            projectMemory.narrativeStyle = `CINEMATIC 3D EXPERIENCE: Create an Awwwards-level immersive 3D website for: ${state.userPrompt.slice(0, 300)}.
QUALITY: Every scene must be a MURAL (200+ lines, custom shaders, particle systems, scroll narratives) not a thumbnail.
SCROLL NARRATIVE: Map useScroll().offset to 3-act arc (Establish->Reveal->Resolve).
CAMERA: Use CatmullRomCurve3 for cinematic camera fly-throughs on hero scenes.
SHADERS: Include custom ShaderMaterial with vertexShader + fragmentShader + uTime for atmospheric backgrounds.
PARTICLES: Use BufferGeometry particle morphing systems that transition between shapes on scroll.
POSTPROCESSING: Bloom, Vignette, ChromaticAberration animated with scroll via refs.
Canvas: gl={{ antialias: true, alpha: false, powerPreference: "high-performance" }} dpr={[1,2]} shadows camera={{ fov: 60, near: 0.1, far: 1000 }}
ScrollControls: pages={8} damping={0.03}
Performance: <AdaptiveDpr pixelated /> <AdaptiveEvents />`;
        }
        console.log(`[blueprint] Project brain initialized (3D=${projectMemory.is3D})`);

        return {
            blueprint,
            projectId,
            availableImages,
            dynamicTheme,
            projectMemory,
            detailedContext: planBlueprint.detailedContext || '',
            workflowNodes: planBlueprint.workflow?.nodes || [],
            workflowEdges: planBlueprint.workflow?.edges || [],
            currentPhase: 'blueprint',
            messages: [
                ` Autonomous Planning Complete: ${blueprint.projectName}`,
                ` Theme: ${dynamicTheme.palette.name} + ${dynamicTheme.layout.name}`,
                ` ${blueprint.pages.length} pages dynamically determined`,
                ` ${blueprint.features.length} features identified`,
                ` ${availableImages.length} images ready`,
                state.enable3D ? ` 3D dependencies injected into blueprint` : ''
            ].filter(Boolean)
        };

    } catch (error: any) {
        console.error(' Blueprint generation failed:', error.message);
        throw error;
    }
}

function extractBusinessName(prompt: string): string {
    const explicitMatch = prompt.match(
        /(?:for|called|named)\s+["']?([A-Z][a-zA-Z0-9\s&'.,-]{2,40})["']?(?:\s|$|,)/
    );
    if (explicitMatch) return explicitMatch[1].trim();

    const quotedMatch = prompt.match(/["']([A-Z][a-zA-Z0-9\s&'.]{2,40})["']/);
    if (quotedMatch) return quotedMatch[1].trim();

    return prompt
        .replace(/^(create|build|make|design|develop|generate)\s+(a\s+|an\s+|the\s+)?/i, '')
        .split(/\s+/)
        .slice(0, 4)
        .map((w, i) => i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : w)
        .join(' ');
}

/**
 * Extract pages using LLM - truly dynamic, project-specific page generation
 * This replaces the old keyword-based approach with intelligent LLM analysis
 */

// Multiple API keys for rotation in blueprint node
const blueprintApiKeys = [
    process.env.gemini8,
    process.env.gemini9,
    process.env.gemini10,
    process.env.gemini11,
    process.env.gemini,
    process.env.gemini3,
    process.env.gemini4,
    process.env.gemini7,
    process.env.gemini6,
    process.env.gemini5,
    process.env.gemini2,
].filter(key => key && key.length > 0) as string[];

let blueprintKeyIndex = Math.floor(Math.random() * Math.max(blueprintApiKeys.length, 1));

function getBlueprintApiKey(): string {
    return blueprintApiKeys[blueprintKeyIndex] || process.env.gemini2 || '';
}

function rotateBlueprintKey(): void {
    if (blueprintApiKeys.length > 1) {
        blueprintKeyIndex = (blueprintKeyIndex + 1) % blueprintApiKeys.length;
        console.log(`[Blueprint] Rotated to key ${blueprintKeyIndex + 1}/${blueprintApiKeys.length}`);
    }
}

async function extractPagesWithLLM(userPrompt: string, detailedContext: string, features: any[]): Promise<any[]> {
    const OpenAI = (await import('openai')).default;

    const featureNames = features.map(f => typeof f === 'string' ? f : f.name || f).join(', ');

    const prompt = `You are an expert web architect. Based on the project requirements, determine the EXACT pages this SPECIFIC project needs.

PROJECT REQUIREMENT: "${userPrompt}"

IDENTIFIED FEATURES: ${featureNames}

DETAILED CONTEXT (excerpt):
${detailedContext.slice(0, 6000)}

===================================================================
CRITICAL RULES:
===================================================================

1. Pages must be UNIQUE to THIS specific project type
2. DO NOT use generic pages unless explicitly needed
3. Think about what makes THIS project special

EXAMPLES OF PROJECT-SPECIFIC PAGES:

For "ChatGPT-like AI chat bot":
- ChatPage (/chat) - Main chat interface
- ConversationHistoryPage (/history) - Past conversations
- ModelsPage (/models) - AI model selection
- APIDocsPage (/api-docs) - API documentation
- SettingsPage (/settings) - User preferences
 NOT: CartPage, BlogPage, ServicesPage

For "Artist portfolio website":
- GalleryPage (/gallery) - Art collection grid
- ArtworkDetailPage (/artwork/:id) - Single artwork view
- CommissionsPage (/commissions) - Commission requests
- ExhibitionsPage (/exhibitions) - Past/upcoming shows
- AboutArtistPage (/about) - Artist biography
 NOT: CartPage, DashboardPage, BlogPage

For "Cake selling bakery":
- CakesPage (/cakes) - Cake catalog
- CustomOrderPage (/custom-order) - Custom cake builder
- FlavorPage (/flavors) - Flavor options
- OrderStatusPage (/order-status) - Track orders
- GalleryPage (/gallery) - Past creations
 NOT: Generic ProductsPage, ServicesPage

For "Fitness tracking app":
- WorkoutsPage (/workouts) - Exercise library
- ProgressPage (/progress) - Stats and charts
- NutritionPage (/nutrition) - Meal tracking
- ChallengesPage (/challenges) - Fitness challenges
- ProfilePage (/profile) - User stats
 NOT: BlogPage, TestimonialsPage

===================================================================

Now, for the project "${userPrompt}", generate 5-8 UNIQUE pages.

Return ONLY a valid JSON array with this exact structure:
[
  {
    "name": "PageName",
    "route": "/route-path",
    "description": "Specific description for this project",
    "sections": ["Section1", "Section2", "Section3"],
    "components": ["Component1", "Component2"]
  }
]

IMPORTANT:
- First page should be HomePage with route "/"
- Last page should be NotFoundPage with route "*"
- All other pages should be UNIQUE to this project type
- Use descriptive, project-specific names (e.g., "ChatPage" not "MainPage")
- Include 5-8 pages total`;

    const maxRetries = 3;
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            rotateBlueprintKey();
            const openai = new OpenAI({
                apiKey: getBlueprintApiKey(),
                baseURL: "https://generativelanguage.googleapis.com/v1beta/openai/"
            });

            const response = await openai.chat.completions.create({
                model: "gemini-2.5-flash-lite",
                messages: [
                    {
                        role: "system",
                        content: "You are a web architect who creates unique, project-specific page structures. You NEVER use generic templates. Return ONLY valid JSON arrays."
                    },
                    { role: "user", content: prompt }
                ],
                temperature: 0.7
            });

            const content = response.choices[0].message.content || '[]';

            // Extract JSON from response
            const jsonMatch = content.match(/\[[\s\S]*\]/);
            if (jsonMatch) {
                const pages = JSON.parse(jsonMatch[0]);
                console.log(`    LLM generated ${pages.length} unique pages for this project`);
                return pages;
            }
        } catch (error: any) {
            console.error(`[Blueprint] Attempt ${attempt} failed:`, error.message);
            rotateBlueprintKey();
            if (attempt < maxRetries) {
                await new Promise(r => setTimeout(r, 1000 * attempt));
                continue;
            }
        }
    }

    // Minimal fallback - ONLY if all retries fail
    console.log('    LLM page extraction failed, using minimal fallback pages');
    return [
        {
            name: 'HomePage',
            route: '/',
            description: 'Main landing page',
            sections: ['Hero', 'Features', 'CTA'],
            components: ['Hero', 'FeatureGrid']
        },
        {
            name: 'NotFoundPage',
            route: '*',
            description: '404 error page',
            sections: ['ErrorMessage'],
            components: ['ErrorDisplay']
        }
    ];
}

/**
 * Synchronous fallback for extractPagesFromContext - used when async not available
 * This is a minimal version that relies on LLM context parsing
 */
function extractPagesFromContext(context: string, features: any[]): any[] {
    // This function now just returns minimal pages
    // The real work is done by extractPagesWithLLM in blueprintNode
    const pages: any[] = [];

    // Always include HomePage
    pages.push({
        name: 'HomePage',
        route: '/',
        description: 'Main landing page with hero section',
        sections: ['Hero', 'Features', 'CTA'],
        components: ['Hero', 'FeatureGrid', 'CallToAction']
    });

    // Parse the context for explicit page mentions
    const contextLower = context.toLowerCase();

    // Look for PAGE_ARCHITECTURE section in context
    const pageArchMatch = context.match(/PAGE_ARCHITECTURE:([\s\S]*?)(?=\n\n|$)/i);
    if (pageArchMatch) {
        const pageLines = pageArchMatch[1].split('\n').filter(l => l.includes('/'));
        for (const line of pageLines) {
            const match = line.match(/(\w+Page)\s*\(["']?([^"')]+)["']?\)/i);
            if (match && match[1] !== 'HomePage') {
                pages.push({
                    name: match[1],
                    route: match[2],
                    description: line.split('-')[1]?.trim() || match[1],
                    sections: ['MainContent'],
                    components: []
                });
            }
        }
    }

    // Always add 404 page
    pages.push({
        name: 'NotFoundPage',
        route: '*',
        description: '404 error page',
        sections: ['ErrorMessage', 'BackButton'],
        components: ['ErrorDisplay']
    });

    return pages;
}

/**
 * Extract components from detailedContext
 */
function extractComponentsFromContext(context: string): any[] {
    // Base UI components that are always needed
    const baseComponents = [
        { name: 'Button', type: 'ui', props: ['children', 'variant', 'size', 'onClick', 'disabled', 'loading'] },
        { name: 'Card', type: 'ui', props: ['children', 'className', 'hover'] },
        { name: 'Input', type: 'ui', props: ['placeholder', 'value', 'onChange', 'type', 'error'] },
        { name: 'Modal', type: 'ui', props: ['isOpen', 'onClose', 'title', 'children'] },
        { name: 'Badge', type: 'ui', props: ['children', 'variant', 'size'] },
        { name: 'Avatar', type: 'ui', props: ['src', 'alt', 'size', 'fallback'] },
        { name: 'Skeleton', type: 'ui', props: ['width', 'height', 'className'] },
        { name: 'Spinner', type: 'ui', props: ['size', 'className'] },
        { name: 'Toast', type: 'ui', props: ['message', 'type', 'duration'] },
        { name: 'Tooltip', type: 'ui', props: ['content', 'children', 'position'] },
        { name: 'Tabs', type: 'ui', props: ['tabs', 'activeTab', 'onChange'] },
        { name: 'Accordion', type: 'ui', props: ['items', 'allowMultiple'] },
        { name: 'Dropdown', type: 'ui', props: ['trigger', 'items', 'onSelect'] },
    ];

    // Layout components
    const layoutComponents = [
        { name: 'Header', type: 'layout', props: ['logo', 'navItems', 'sticky'] },
        { name: 'Footer', type: 'layout', props: ['links', 'social', 'copyright'] },
        { name: 'Sidebar', type: 'layout', props: ['items', 'collapsed', 'onToggle'] },
        { name: 'Container', type: 'layout', props: ['children', 'maxWidth', 'className'] },
        { name: 'Section', type: 'layout', props: ['children', 'id', 'className', 'background'] },
    ];

    // Feature components based on context keywords
    const featureComponents: any[] = [];
    const contextLower = context.toLowerCase();

    if (contextLower.includes('product') || contextLower.includes('shop')) {
        featureComponents.push(
            { name: 'ProductCard', type: 'feature', props: ['product', 'onAddToCart'] },
            { name: 'ProductGrid', type: 'feature', props: ['products', 'columns'] },
            { name: 'FilterBar', type: 'feature', props: ['filters', 'onFilterChange'] },
            { name: 'CartItem', type: 'feature', props: ['item', 'onRemove', 'onQuantityChange'] }
        );
    }

    if (contextLower.includes('testimonial') || contextLower.includes('review')) {
        featureComponents.push(
            { name: 'TestimonialCard', type: 'feature', props: ['testimonial'] },
            { name: 'TestimonialSlider', type: 'feature', props: ['testimonials', 'autoPlay'] },
            { name: 'RatingStars', type: 'feature', props: ['rating', 'maxStars'] }
        );
    }

    if (contextLower.includes('pricing') || contextLower.includes('plan')) {
        featureComponents.push(
            { name: 'PricingCard', type: 'feature', props: ['plan', 'popular', 'onSelect'] },
            { name: 'PricingTable', type: 'feature', props: ['plans', 'features'] },
            { name: 'FeatureCheck', type: 'feature', props: ['feature', 'included'] }
        );
    }

    if (contextLower.includes('dashboard') || contextLower.includes('stat')) {
        featureComponents.push(
            { name: 'StatCard', type: 'feature', props: ['title', 'value', 'change', 'icon'] },
            { name: 'Chart', type: 'feature', props: ['data', 'type', 'options'] },
            { name: 'ActivityFeed', type: 'feature', props: ['activities', 'maxItems'] }
        );
    }

    if (contextLower.includes('blog') || contextLower.includes('article')) {
        featureComponents.push(
            { name: 'BlogCard', type: 'feature', props: ['post', 'compact'] },
            { name: 'BlogPost', type: 'feature', props: ['content', 'author', 'date'] },
            { name: 'AuthorCard', type: 'feature', props: ['author'] }
        );
    }

    if (contextLower.includes('contact') || contextLower.includes('form')) {
        featureComponents.push(
            { name: 'ContactForm', type: 'feature', props: ['onSubmit', 'fields'] },
            { name: 'NewsletterForm', type: 'feature', props: ['onSubscribe'] }
        );
    }

    if (contextLower.includes('team') || contextLower.includes('member')) {
        featureComponents.push(
            { name: 'TeamMember', type: 'feature', props: ['member'] },
            { name: 'TeamGrid', type: 'feature', props: ['members', 'columns'] }
        );
    }

    // Hero and CTA are always useful
    featureComponents.push(
        { name: 'Hero', type: 'feature', props: ['title', 'subtitle', 'cta', 'image'] },
        { name: 'CallToAction', type: 'feature', props: ['title', 'description', 'buttonText', 'onAction'] },
        { name: 'FeatureGrid', type: 'feature', props: ['features', 'columns'] },
        { name: 'FeatureCard', type: 'feature', props: ['icon', 'title', 'description'] }
    );

    return [...layoutComponents, ...baseComponents, ...featureComponents];
}

/**
 * Extract design system from detailedContext
 */
function extractDesignSystem(context: string): any {
    // Default modern design system
    const defaultDesign = {
        primaryColor: '#6366f1', // Indigo
        secondaryColor: '#8b5cf6', // Violet
        accentColor: '#10b981', // Emerald
        style: 'modern',
        fonts: ['Inter', 'system-ui', 'sans-serif']
    };

    // Try to extract colors from context
    const colorMatch = context.match(/(#[0-9A-Fa-f]{6})/g);
    if (colorMatch && colorMatch.length >= 2) {
        defaultDesign.primaryColor = colorMatch[0];
        defaultDesign.secondaryColor = colorMatch[1];
        if (colorMatch.length >= 3) {
            defaultDesign.accentColor = colorMatch[2];
        }
    }

    // Determine style from keywords
    const contextLower = context.toLowerCase();
    if (contextLower.includes('minimal') || contextLower.includes('clean')) {
        defaultDesign.style = 'minimal';
    } else if (contextLower.includes('playful') || contextLower.includes('fun') || contextLower.includes('colorful')) {
        defaultDesign.style = 'playful';
    } else if (contextLower.includes('corporate') || contextLower.includes('professional') || contextLower.includes('business')) {
        defaultDesign.style = 'corporate';
    } else if (contextLower.includes('dark') || contextLower.includes('modern')) {
        defaultDesign.style = 'modern';
    }

    return defaultDesign;
}

export { STANDARD_DEPENDENCIES, DEV_DEPENDENCIES };
